### ISSUE TITLE
请问哪里能找到stub.dll的代码呢

### ISSUE THREAD

**Issue by finch7** [longqun/Packer#1]
请问哪里能找到stub.dll的代码呢
谢谢了

**Comment by longqun** [comment]
外面还有repo叫做Stub，应该把两个repo合并的。

**Comment by longqun** [comment]
> 请问哪里能找到stub.dll的代码呢
> 谢谢了

在外面还有一个Stub的repo，这两个repo应该合并的。

**Comment by longqun** [comment]
现在把两个repo合在一起了
