### ISSUE TITLE
新手请教

### ISSUE THREAD

**Issue by Ahaixi** [longqun/Packer#4]
问一下可以使用你的项目做毕设吗

**Comment by longqun** [comment]
of course

**Comment by Ahaixi** [comment]
我想问一下：我运行加密之后的exe，输入密码之后为啥就没有反应了，是因为解压数据时的重定位出错了吗

**Comment by Ahaixi** [comment]
大佬，可以私聊私聊吗，我想请教您几个问题，看发邮箱您好像没注意

**Comment by Ahaixi** [comment]
> 问一下可以使用你的项目做毕设吗
